### ISSUE TITLE
JSON decode issue when querying database

### ISSUE THREAD

**Issue by slzatz** [jamesmoss/flywheel#22]
Version is 0.44 running on python 3.43 under Windows 7
The db structure is:

class scrobble(Model):
    artist = Field(hash_key=True)
    ts = Field(data_type=datetime, range_key=True) 

Works fine when database is queried through boto or when exploring through the DynamoDB Web interface

However, all queries are throwing an Exception as follows:

    >>> z = engine(scrobble).filter(artist="Lucinda Williams")
    >>> z.first()
    Traceback (most recent call last):
       File "<stdin>", line 1, in <module>
      File "C:\Python34\lib\site-packages\flywheel\query.py", line 155, in first
    attributes=attributes, filter_or=filter_or):
      File "C:\Python34\lib\site-packages\flywheel\query.py", line 80, in gen
    yield self.model.ddb_load_(self.engine, result)
      File "C:\Python34\lib\site-packages\flywheel\models.py", line 458, in ddb_load_
    obj.set_ddb_val_(key, val)
      File "C:\Python34\lib\site-packages\flywheel\models.py", line 450, in set_ddb_val_
    setattr(self, key, Field.ddb_load_overflow(val))
      File "C:\Python34\lib\site-packages\flywheel\fields\__init__.py", line 265, in ddb_load_overflow
    return json.loads(val)
      File "C:\Python34\lib\json\__init__.py", line 318, in loads
    return _default_decoder.decode(s)
      File "C:\Python34\lib\json\decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
      File "C:\Python34\lib\json\decoder.py", line 361, in raw_decode
        raise ValueError(errmsg("Expecting value", s, err.value)) from None
    ValueError: Expecting value: line 1 column 1 (char 0)

**Comment by jamesmoss** [comment]
This is a PHP project, not Python. I think you want https://github.com/mathcamp/flywheel

**Comment by slzatz** [comment]
sorry
